# Site Configuration
# Global settings for the portfolio website

site:
  name: "Karthikeyan K Portfolio"
  description: "Personal portfolio showcasing my work and journey as a developer"
  url: "https://yourportfolio.com"
  author: "Karthikeyan K"
  
# SEO Settings
seo:
  title: "Karthikeyan K - Full Stack Developer"
  description: "Portfolio of Karthikeyan K, a passionate Full Stack Developer specializing in modern web technologies"
  keywords: ["portfolio", "developer", "web development", "full stack", "react", "nextjs"]
  og_image: "/og-image.jpg"
  
# Navigation
navigation:
  - name: "Home"
    href: "/"
  - name: "About"
    href: "/about"
  - name: "Projects"
    href: "/projects"
  - name: "Contact"
    href: "/contact"

# Footer Settings
footer:
  description: "Crafting delightful web experiences with code, design, and curiosity."
  thanks_message: "Thanks for stopping by!"
  copyright: "© 2025 Karthikeyan K | Portfolio. All rights reserved."
  
# Theme Settings
theme:
  primary_color: "#b98fff"
  background_color: "#0b0b0f"
  text_color: "#ffffff"
  accent_color: "#7a6fff"

# Banner Settings
# Control the work in progress banner visibility and message
banner:
  show_work_in_progress: false  # Set to false to hide the banner
  message: "Work in Progress: This portfolio is currently under development. Some features may be incomplete or subject to change."
